question_data = [
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy", "question": "The name of the main character of the video game 'The Legend of Zelda', is Zelda.", "correct_answer": "False", "incorrect_answers": ["True"]}, 
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy", "question": "The game 'Battlefield 1' takes place during World War I.", "correct_answer": "True", "incorrect_answers": ["False"]}, 
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy", "question": "Pac-Man was invented by the designer Toru Iwatani while he was eating pizza.", "correct_answer": "True", "incorrect_answers": ["False"]}, 
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy", "question": "In 'Sonic Adventure', you are able to transform into Super Sonic at will after completing the main story.", "correct_answer": "False", "incorrect_answers": ["True"]}, 
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy", "question": "In Team Fortress 2, being disguised as a scout or medic results in a speed boost.", "correct_answer": "False", "incorrect_answers": ["True"]}, 
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy", "question": "In the 'Half-Life' series, 'H.E.V' stands for 'Hazardous Evasiveness Vest'", "correct_answer": "False", "incorrect_answers": ["True"]}, 
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy", "question": "The main playable character of the 2015 RPG 'Undertale' is a monster.", "correct_answer": "False", "incorrect_answers": ["True"]}, 
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy", "question": "The ghosts in 'Pac-Man' and 'Ms. Pac-Man' have completely different behavior.", "correct_answer": "True", "incorrect_answers": ["False"]}, 
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy", "question": "In the 'S.T.A.L.K.E.R.' series, the Freedom faction wishes to destroy the supernatural area known as  'the Zone'.", "correct_answer": "False", "incorrect_answers": ["True"]}, 
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy", "question": "The shotgun appears in every numbered Resident Evil game.", "correct_answer": "True", "incorrect_answers": ["False"]}]
